### ISSUE TITLE
Trash icon bug 

### ISSUE THREAD

**Issue by APakrohk** [simpleit/docky#11]
operating system : xubuntu 17.10
![screenshot_2018-02-18_19-19-54](https://user-images.githubusercontent.com/27810360/36355320-94307be8-14f6-11e8-9ad2-4aa85704c163.png)

**Comment by stuff** [comment]
I'm pretty sure you opened an issue at the wrong place :)

**Comment by APakrohk** [comment]
I have this problem in the docky.

**Comment by adrien-gueret** [comment]
@APakrohk You are not in the good place: this Docky project is NOT the one you are using. Even if the names are the same, they are two totally different projects.

Please report your bug on the correct project, probably here: https://launchpad.net/docky
